meta_title: "Monsieur Macaron"
meta_description: "Monsieur Macaron - French Pastries and Macarons based in Hawke's Bay New Zealand"
meta_image: "cachetmacaron.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "monsieurmacaron"
